<?php

namespace Skrepka\CategoryBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DocumentRepository
{
    public function getParentName()
    {

        var_dump($this->getParent());
        return null;
        if (is_null($this->getParent())) {
            return $this->getName();
        }
//        die('dd');
//        var_dump($this->getCategories());
        return null;
    }
}