company:
    pattern:  /
    defaults: { _controller: CompanyBundle:Company:index }

company_show:
    pattern:  /{slug}
    defaults: { _controller: CompanyBundle:Company:show }

company_edit:
    pattern:  /{id}/edit
    defaults: { _controller: CompanyBundle:Company:edit }

company_delete:
    pattern:  /{id}/delete
    defaults: { _controller: CompanyBundle:Company:delete }

company_new:
    pattern:  /new/
    defaults: { _controller: CompanyBundle:Company:new }

company_create:
    pattern:  /create
    defaults: { _controller: CompanyBundle:Company:create }