company:
    pattern:  /companies
    defaults: { _controller: CompanyBundle:Company:index }

company_edit:
    pattern:  /company/{slug}/edit
    defaults: { _controller: CompanyBundle:Company:edit }

company_update:
    pattern:  /company/{id}/update
    defaults: { _controller: CompanyBundle:Company:update }

company_delete:
    pattern:  /company/{id}/delete
    defaults: { _controller: CompanyBundle:Company:delete }

company_new:
    pattern:  /company/new
    defaults: { _controller: CompanyBundle:Company:new }

company_create:
    pattern:  /company/create
    defaults: { _controller: CompanyBundle:Company:create }