company:
    pattern:  /companies
    defaults: { _controller: CompanyBundle:Company:index }

company_show:
    pattern:  /{slug}/
    defaults: { _controller: CompanyBundle:Company:show }

company_edit:
    pattern:  /company/{id}/edit
    defaults: { _controller: CompanyBundle:Company:edit }

company_delete:
    pattern:  /company/{id}/delete
    defaults: { _controller: CompanyBundle:Company:delete }

company_new:
    pattern:  /company/new
    defaults: { _controller: CompanyBundle:Company:new }

company_create:
    pattern:  /company/create
    defaults: { _controller: CompanyBundle:Company:create }